# fly.toml app configuration file generated for fab-leaderboard on 2023-05-30T17:25:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fab-leaderboard"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]
  [build.args]
    BP_KEEP_FILES = "resources/*"

[env]
  PRIMARY_REGION = "lhr"
