# fly.toml file generated for fab-leaderboard on 2023-04-16T16:03:20+01:00

app = "fab-leaderboard"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lhr"
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]
  BP_KEEP_FILES = "countries.yml"
